### PR TITLE
docs: add AUR package in README.md

### PR DESCRIPTION
**Pull request by neruyzo**
I created a package for Archlinux in AUR https://aur.archlinux.org/packages/rumqttd-bin.

Maybe the systemd service is not perfect but works https://git.sr.ht/~mekyt/rumqttd-bin/tree/master/item/rumqtt.service.

### CODE REVIEW

**Review by henil — COMMENTED** [review]
can you add the heading to https://github.com/bytebeamio/rumqtt#contents as well

**Comment by neruyzo** [comment]
> can you add the heading to https://github.com/bytebeamio/rumqtt#contents as well

My bad, thanks, it's done

**Comment by henil** [comment]
also this being a rust project i think aur helper being `paru` is more appropriate :), added a note for people using anything else.

**Comment by henil** [comment]
Thank you :rocket:

**Pull request merged**
