### PR TITLE
Add `from_senders` for the Sync Client

### PR DESCRIPTION
**Pull request by BKDaugherty**
A lot of my team's code uses the synchronous client. I'd like to be able to easily write tests using a Fake Mqtt client. One easy way to do this for unit tests is by using something like the `from_senders` method that's available on the `AsyncClient`. This PR adds a `from_sender` method for the sync client which can be used to write tests like the one I wrote in this PR. 

It also updates a stale comment on the async client.

## Type of change

New feature (non-breaking change which adds functionality)

## Checklist:

- [X] Formatted with `cargo fmt`
- [X] Make an entry to `CHANGELOG.md` if it's relevant to the users of the library. If it's not relevant mention why.

### CODE REVIEW

**Review by swanandx — CHANGES_REQUESTED** [review]
Thanks for the PR and your patience! 

Can you please add the same changes for `v5/client` as well? so we can stay consistent!

**Comment by BKDaugherty** [comment]
Yeah absolutely!

**Comment by swanandx** [comment]
any updates @BKDaugherty ?

**Comment by BKDaugherty** [comment]
> any updates @BKDaugherty ?

Hey! Sorry @swanandx, I was AFK a bit for the holidays. Just updated to add this to the v5 client as well! Is there a proposal at all for unifying these? Would be curious to see that

**Review by swanandx — APPROVED** [review]

**Comment by swanandx** [comment]
> I was AFK a bit for the holidays. Just updated to add this to the v5 client as well!
>

Oh no worries, Thank you so much!

> Is there a proposal at all for unifying these? Would be curious to see that
>
I was thinking about it, but then how would be distinguish between v4 & v5 clients? we might need to store a field like `protocol` in client and choose `publish` / `subscribe` based on it, otherwise introduce generics or something. I thought it might add much more complexity, if you think that isn't the case, feel free to open a RFC, would definitely love to see it :)

 > Hm. Any idea why the macos tests would fail? Doesn't seem related to this
 >
 i don't have that idea either haha, it keeps failing randomly. so we can ignore it

**Pull request merged**
