### PR TITLE
chore: docker image based on distroless & build and docker scripts

### PR DESCRIPTION
**Pull request by carlocorradini**
Related to PR #671 

What has been changed:

- `rumqttd` Docker image is based on distroless rather than `Alpine`
   Docker image is now based on `gcr.io/distroless/cc` (from Google) to enhance overall security since _"it does not contain package managers, shells or any other programs you would expect to find in a standard Linux distribution"_

- More robust and fully configurable scripts (see `scripts` and `rumqttd/scripts` directories). Also `POSIX` compliant
    1. `rumqttd/scripts/docker.sh`
        Build and push `rumqttd` Docker image
    2. `rumqttd/scripts/build.sh`
        Build `rumqttd` using `Cross`

   Note that both scripts are configurable and also have an helper flag (`--help`)

### CODE REVIEW

**Comment by carlocorradini** [comment]
@de-sh Any update? 🤗🥳

**Comment by carlocorradini** [comment]
@swanandx @henil  Any thoughts on this? I apologize for pinging

**Comment by henil** [comment]
i think the script is very complicated and i am not sure that its really necessary. and for distroless docker image what are the advantage to use those instead of what we have currently?

**Comment by carlocorradini** [comment]
I believe the numerous papers on Distroless vs Alpine can explain it far better than I can.😂😅
See [this](https://www.sumup.com/careers/techstories/stop-using-alpine-docker-images) or [this](https://www.reddit.com/r/devops/comments/dtd2mu/distroless_docker_images_thoughts) or ...

**Comment by carlocorradini** [comment]
These scripts are quite user-friendly (with `--help` and args configuration) and `POSIX` compliant

**Comment by carlocorradini** [comment]
The `main` parts are a few lines of code:

`build.sh`
image

`docker.sh`
image

Easy peasy

**Pull request closed without merging**
