### PR TITLE
Update tokio to 0.3

### PR DESCRIPTION
**Pull request by jakubtrnka**
I upgraded tokio to version 0.3.

### CODE REVIEW

**Comment by jakubtrnka** [comment]
I'm not sure what to do about the failing test

**Comment by tekjar** [comment]
Nice!! Thank yo :) How does this affect users on tokio 0.2?

**Comment by jakubtrnka** [comment]
Users of tokio 0.2 need to upgrade. It is not possible to run it on tokio 0.2 runtime.

However, for this reason we have semantic versioning ;) Users who wish to stay at tokio 0.2 may restrict rumqttc dependency to "^0.2"

**Comment by jplatte** [comment]
There's multiple compatibility layers for different async runtimes and tokio 0.2 + tokio 0.3 is no exception. A quick search turned up https://github.com/LucioFranco/tokio-compat-02 for me.

**Comment by jakubtrnka** [comment]
I need to reopen the PR from different repo

**Pull request closed without merging**
