### PR TITLE
Allow modifying websocket requests.

### PR DESCRIPTION
**Pull request by reitermarkus**
I am trying to connect to an AWS IoT Shadow via MQTT and SigV4 but couldn't find any way to add additional headers to the request. This adds a way to modify the request before connecting.

Example usage:

```rust
    mqtt_options.set_request_modifier(move |request| {
      let credential_provider = credential_provider.clone();
      let region = region.clone();

      async move {
          let request_config = RequestConfig {
              request_ts: SystemTime::now(),
              region: &SigningRegion::from(region.clone()),
              service: &SigningService::from_static("iotdata"),
              payload_override: None,
          };

        let (parts, body) = request.into_parts();
        let mut request: http::Request<SdkBody> = http::Request::from_parts(parts, SdkBody::empty());

        let signer = SigV4Signer::new();
        signer.sign(
          &OperationSigningConfig::default_config(),
          &request_config,
          &credential_provider.provide_credentials().await.unwrap(),
          &mut request,
        ).unwrap();

        let (parts, _) = request.into_parts();
        http::Request::from_parts(parts, body)
      }
    });
```

## Type of change

- New feature (non-breaking change which adds functionality)

## Checklist:

- [x] Formatted with `cargo fmt`
- [x] Make an entry to `CHANGELOG.md` if its relevant of user of the library. If its not relevant mention why.

### CODE REVIEW

**Comment by henil** [comment]
@reitermarkus can you check CI failures? 

Also I am not sure if the updated `Cargo.lock` file is required here, remove it if its not relevant with this changes.

**Comment by reitermarkus** [comment]
Added `#[cfg(feature = "websocket")]` for the added parts and removed the `Cargo.lock` changes.

**Comment by reitermarkus** [comment]
Added a `RequestModifierFn` type alias to fix the complex type warning.

**Comment by reitermarkus** [comment]
Well, I only need to set the auth/signature headers, so I don't want to also have to set all MQTT protocol-specific headers.

Also, the AWS `ProvideCredentials` trait may be implemented in a such way that credentials are automatically refreshed, so no additional changes would be necessary when reconnecting.

**Comment by reitermarkus** [comment]
That seems very unergonomic and unintuitive to use. I'd have to create an empty request with the URL I already passed to `MqttOptions::new`.

**Comment by reitermarkus** [comment]
To get the headers I would still have to create a request, since signing is done on a fully formed request. There is no way to only get signature headers without a request in the first place.

**Comment by yatinmaan** [comment]
> To get the headers I would still have to create a request, since signing is done on a fully formed request. There is no way to only get signature headers without a request in the first place.

@reitermarkus Makes sense. That's the sort of stuff I was look for when I asked.

>> Unless there's a use case I missed which can't be serviced like this?

Sorry for the delay and thanks for your contribution :rocket:

**Comment by reitermarkus** [comment]
@yatinmaan, could you release a new version with this included? Thanks.

**Comment by yatinmaan** [comment]
> @yatinmaan, could you release a new version with this included? Thanks.

@swanandx ^^

**Comment by swanandx** [comment]
thnx for the ping @yatinmaan ! We will release rumqttc this week @reitermarkus  :100:

**Comment by swanandx** [comment]
update: rumqttc v0.23.0 is released, which includes this change!

**Pull request merged**
